export const ingredients = [
  "Light rum",
  "Applejack",
  "Gin",
  "Dark rum",
  "Sweet Vermouth",
  "Strawberry schnapps",
  "Scotch",
  "Apricot brandy",
  "Triple sec",
  "Southern Comfort",
  "Orange bitters",
  "Brandy",
  "Lemon vodka",
  "Blended whiskey",
  "Dry Vermouth",
  "Amaretto",
  "Tea",
  "Champagne",
  "Coffee liqueur",
  "Bourbon",
  "Tequila",
  "Vodka",
  "Añejo rum",
  "Bitters",
  "Sugar",
  "Kahlua",
  "demerara Sugar",
  "Dubonnet Rouge",
  "Watermelon",
  "Lime juice",
  "Irish whiskey",
  "Apple brandy",
  "Carbonated water",
  "Cherry brandy",
  "Creme de Cacao",
  "Grenadine",
  "Port",
  "Coffee brandy",
  "Red wine",
  "Rum",
  "Grapefruit juice",
  "Ricard",
  "Sherry",
  "Cognac",
  "Sloe gin",
  "Apple juice",
  "Pineapple juice",
  "Lemon juice",
  "Sugar syrup",
  "Milk",
  "Strawberries",
  "Chocolate syrup",
  "Yoghurt",
  "Mango",
  "Ginger",
  "Lime",
  "Cantaloupe",
  "Berries",
  "Grapes",
  "Kiwi",
  "Tomato juice",
  "Cocoa powder",
  "Chocolate",
  "Heavy cream",
  "Galliano",
  "Peach Vodka",
  "Ouzo",
  "Coffee",
  "Spiced rum",
  "Water",
  "Espresso",
  "Angelica root",
  "Orange",
  "Cranberries",
  "Johnnie Walker",
  "Apple cider",
  "Everclear",
  "Cranberry juice",
  "Egg yolk",
  "Egg",
  "Grape juice",
  "Peach nectar",
  "Lemon",
  "Firewater",
  "Lemonade",
  "Lager",
  "Whiskey",
  "Absolut Citron",
  "Pisco",
  "Irish cream",
  "Ale",
  "Chocolate liqueur",
  "Midori melon liqueur",
  "Sambuca",
  "Cider",
  "Sprite",
  "7-Up",
  "Blackberry brandy",
  "Peppermint schnapps",
  "Creme de Cassis",
];

export const sortedIngredients = [
  "7-Up",
  "Absolut Citron",
  "Ale",
  "Amaretto",
  "Angelica root",
  "Apple brandy",
  "Apple cider",
  "Apple juice",
  "Applejack",
  "Apricot brandy",
  "Añejo rum",
  "Berries",
  "Bitters",
  "Blackberry brandy",
  "Blended whiskey",
  "Bourbon",
  "Brandy",
  "Cantaloupe",
  "Carbonated water",
  "Champagne",
  "Cherry brandy",
  "Chocolate",
  "Chocolate liqueur",
  "Chocolate syrup",
  "Cider",
  "Cocoa powder",
  "Coffee",
  "Coffee brandy",
  "Coffee liqueur",
  "Cognac",
  "Cranberries",
  "Cranberry juice",
  "Creme de Cacao",
  "Creme de Cassis",
  "Dark rum",
  "Demerara Sugar",
  "Dry Vermouth",
  "Dubonnet Rouge",
  "Egg",
  "Egg yolk",
  "Espresso",
  "Everclear",
  "Firewater",
  "Galliano",
  "Gin",
  "Ginger",
  "Grape juice",
  "Grapefruit juice",
  "Grapes",
  "Grenadine",
  "Heavy cream",
  "Irish cream",
  "Irish whiskey",
  "Johnnie Walker",
  "Kahlua",
  "Kiwi",
  "Lager",
  "Lemon",
  "Lemon juice",
  "Lemon vodka",
  "Lemonade",
  "Light rum",
  "Lime",
  "Lime juice",
  "Mango",
  "Midori melon liqueur",
  "Milk",
  "Orange",
  "Orange bitters",
  "Ouzo",
  "Peach Vodka",
  "Peach nectar",
  "Peppermint schnapps",
  "Pineapple juice",
  "Pisco",
  "Port",
  "Red wine",
  "Ricard",
  "Rum",
  "Sambuca",
  "Scotch",
  "Sherry",
  "Sloe gin",
  "Southern Comfort",
  "Spiced rum",
  "Sprite",
  "Strawberries",
  "Strawberry schnapps",
  "Sugar",
  "Sugar syrup",
  "Sweet Vermouth",
  "Tea",
  "Tequila",
  "Tomato juice",
  "Triple sec",
  "Vodka",
  "Water",
  "Watermelon",
  "Whiskey",
  "Yoghurt",
];
