export const ingredients = [
  "151 proof rum",
  "7-up",
  "Absinthe",
  "Absolut Kurant",
  "Absolut Peppar",
  "Absolut Vodka",
  "Absolut citron",
  "Advocaat",
  "Aejo Rum",
  "Aftershock",
  "Agave Syrup",
  "Ale",
  "Allspice",
  "Allspice Dram",
  "Almond",
  "Almond Flavoring",
  "Amaretto",
  "Amaro Montenegro",
  "Angelica Root",
  "Angostura Bitters",
  "Anis",
  "Anise",
  "Anisette",
  "Aperol",
  "Apfelkorn",
  "Apple",
  "Apple Brandy",
  "Apple Cider",
  "Apple Juice",
  "Apple Schnapps",
  "Applejack",
  "Apricot",
  "Apricot Brandy",
  "Apricot Nectar",
  "Aquavit",
  "Arrack",
  "Asafoetida",
  "Averna",
  "Bacardi",
  "Bacardi Limon",
  "Baileys Irish Cream",
  "Banana",
  "Banana Liqueur",
  "Banana Rum",
  "Banana Syrup",
  "Barenjager",
  "Basil",
  "Beef Stock",
  "Beer",
  "Benedictine",
  "Berries",
  "Bitter lemon",
  "Bitters",
  "Black Pepper",
  "Black Rum",
  "Black Sambuca",
  "Blackberries",
  "Blackberry Brandy",
  "Blackberry Schnapps",
  "Blackcurrant Cordial",
  "Blackcurrant Schnapps",
  "Blackcurrant Squash",
  "Blackstrap rum",
  "Blended Scotch",
  "Blended Whiskey",
  "Blood Orange",
  "Blue Curacao",
  "Blue Maui",
  "Blueberries",
  "Blueberry Schnapps",
  "Bourbon",
  "Brandy",
  "Brown Sugar",
  "Butter",
  "Butterscotch Schnapps",
  "Cachaca",
  "Calvados",
  "Campari",
  "Canadian Whisky",
  "Candy",
  "Cantaloupe",
  "Caramel Coloring",
  "Caramel Sauce",
  "Carbonated Soft Drink",
  "Carbonated Water",
  "Cardamom",
  "Cayenne Pepper",
  "Celery",
  "Celery Salt",
  "Chambord Raspberry Liqueur",
  "Champagne",
  "Chareau",
  "Cherries",
  "Cherry",
  "Cherry Brandy",
  "Cherry Cola",
  "Cherry Grenadine",
  "Cherry Heering",
  "Cherry Juice",
  "Cherry Liqueur",
  "Chocolate",
  "Chocolate Ice-cream",
  "Chocolate Liqueur",
  "Chocolate Milk",
  "Chocolate Sauce",
  "Chocolate Syrup",
  "Cider",
  "Cinnamon",
  "Cinnamon Schnapps",
  "Cinnamon Whisky",
  "Citrus Vodka",
  "Clamato Juice",
  "Cloves",
  "Club Soda",
  "Coca-Cola",
  "Cocchi Americano",
  "Cocktail Onion",
  "Cocoa Powder",
  "Coconut Cream",
  "Coconut Liqueur",
  "Coconut Milk",
  "Coconut Rum",
  "Coconut Syrup",
  "Coffee",
  "Coffee Brandy",
  "Coffee Liqueur",
  "Cognac",
  "Cointreau",
  "Cola",
  "Cold Water",
  "Condensed Milk",
  "Coriander",
  "Corn Syrup",
  "Cornstarch",
  "Corona",
  "Cranberries",
  "Cranberry Juice",
  "Cranberry Liqueur",
  "Cranberry Vodka",
  "Cream",
  "Cream Sherry",
  "Cream Soda",
  "Cream of Coconut",
  "Creme De Almond",
  "Creme De Banane",
  "Creme De Cacao",
  "Creme De Cassis",
  "Creme De Noyaux",
  "Creme Fraiche",
  "Creme de Mure",
  "Creme de Violette",
  "Crown Royal",
  "Crystal Light",
  "Cucumber",
  "Cumin Powder",
  "Cumin Seed",
  "Curacao",
  "Cynar",
  "Daiquiri Mix",
  "Dark Chocolate",
  "Dark Creme De Cacao",
  "Dark Rum",
  "Dark Soy Sauce",
  "Demerara Sugar",
  "Diet Coke",
  "Dr. Pepper",
  "Drambuie",
  "Dried Oregano",
  "Dry Curacao",
  "Dry Vermouth",
  "Dubonnet Blanc",
  "Dubonnet Rouge",
  "Egg",
  "Egg White",
  "Egg Yolk",
  "Eggnog",
  "Elderflower cordial",
  "Erin Cream",
  "Espresso",
  "Everclear",
  "Falernum",
  "Fanta",
  "Fennel Seeds",
  "Fernet-Branca",
  "Figs",
  "Firewater",
  "Flaked Almonds",
  "Food Coloring",
  "Forbidden Fruit",
  "Frangelico",
  "Fresca",
  "Fresh Basil",
  "Fresh Lemon Juice",
  "Fresh Lime Juice",
  "Fresh Mint",
  "Fruit",
  "Fruit Juice",
  "Fruit Punch",
  "Galliano",
  "Garlic Sauce",
  "Gatorade",
  "Gin",
  "Ginger",
  "Ginger Ale",
  "Ginger Beer",
  "Ginger Syrup",
  "Glycerine",
  "Godiva Liqueur",
  "Gold Tequila",
  "Gold rum",
  "Goldschlager",
  "Grain Alcohol",
  "Grand Marnier",
  "Granulated Sugar",
  "Grape juice",
  "Grape soda",
  "Grapefruit Juice",
  "Grapes",
  "Green Chartreuse",
  "Green Creme de Menthe",
  "Green Ginger Wine",
  "Green Olives",
  "Grenadine",
  "Ground Ginger",
  "Guava juice",
  "Guinness",
  "Guinness stout",
  "Habanero Peppers",
  "Half-and-half",
  "Hawaiian punch",
  "Hazelnut liqueur",
  "Heavy cream",
  "Honey",
  "Honey syrup",
  "Hooch",
  "Hot Chocolate",
  "Hot Damn",
  "Hot Sauce",
  "Hpnotiq",
  "Ice",
  "Ice-Cream",
  "Iced tea",
  "Ilegal Joven mezcal",
  "Irish Whiskey",
  "Irish cream",
  "Islay single malt Scotch",
  "Jack Daniels",
  "Jagermeister",
  "Jello",
  "Jelly",
  "Jim Beam",
  "Johnnie Walker",
  "Kahlua",
  "Key Largo Schnapps",
  "Kirschwasser",
  "Kiwi",
  "Kiwi liqueur",
  "Kool-Aid",
  "Kummel",
  "Lager",
  "Lavender",
  "Lemon",
  "Lemon Juice",
  "Lemon Peel",
  "Lemon soda",
  "Lemon vodka",
  "Lemon-Lime",
  "Lemon-lime soda",
  "Lemonade",
  "Licorice Root",
  "Light Cream",
  "Light Rum",
  "Lillet",
  "Lillet Blanc",
  "Lime",
  "Lime Juice",
  "Lime Peel",
  "Lime juice cordial",
  "Lime liqueur",
  "Lime vodka",
  "Limeade",
  "Madeira",
  "Malibu Rum",
  "Mandarin",
  "Mandarine napoleon",
  "Mango",
  "Maple syrup",
  "Maraschino Cherry",
  "Maraschino Liqueur",
  "Maraschino cherry juice",
  "Margarita mix",
  "Marjoram leaves",
  "Marshmallows",
  "Martini Bianco",
  "Martini Extra Dry",
  "Martini Rosso",
  "Maui",
  "Melon Liqueur",
  "Melon Vodka",
  "Mezcal",
  "Midori",
  "Midori Melon Liqueur",
  "Milk",
  "Mini-snickers bars",
  "Mint",
  "Mint syrup",
  "Mountain Dew",
  "Nocino",
  "Nutmeg",
  "Olive",
  "Olive Brine",
  "Olive Oil",
  "Onion",
  "Orange",
  "Orange Bitters",
  "Orange Curacao",
  "Orange Juice",
  "Orange Peel",
  "Orange Slice",
  "Orange Soda",
  "Orange liqueur",
  "Orange rum",
  "Orange spiral",
  "Orange vodka",
  "Oreo cookie",
  "Orgeat Syrup",
  "Ouzo",
  "Oyster Sauce",
  "Papaya",
  "Papaya juice",
  "Parfait amour",
  "Passion fruit juice",
  "Passion fruit syrup",
  "Passoa",
  "Peach",
  "Peach Bitters",
  "Peach Nectar",
  "Peach Schnapps",
  "Peach Vodka",
  "Peach brandy",
  "Peach juice",
  "Peach liqueur",
  "Peachtree schnapps",
  "Peanut Oil",
  "Pepper",
  "Peppermint Schnapps",
  "Peppermint extract",
  "Pepsi Cola",
  "Pernod",
  "Peychaud bitters",
  "Pina colada mix",
  "Pineapple",
  "Pineapple Juice",
  "Pineapple Syrup",
  "Pineapple rum",
  "Pineapple vodka",
  "Pineapple-orange-banana juice",
  "Pink lemonade",
  "Pisang Ambon",
  "Pisco",
  "Plain Chocolate",
  "Plain Flour",
  "Plums",
  "Pomegranate juice",
  "Port",
  "Powdered Sugar",
  "Prosecco",
  "Purple passion",
  "Raisins",
  "Ramazzotti",
  "Raspberry Jam",
  "Raspberry Juice",
  "Raspberry Liqueur",
  "Raspberry Vodka",
  "Raspberry cordial",
  "Raspberry schnapps",
  "Raspberry syrup",
  "Red Bull",
  "Red Chile Flakes",
  "Red Chili Flakes",
  "Red Hot Chili Flakes",
  "Red Wine",
  "Rhubarb",
  "Ricard",
  "Rock Salt",
  "Root beer",
  "Root beer schnapps",
  "Rose",
  "Rosemary",
  "Rosemary Syrup",
  "Roses sweetened lime juice",
  "Rosewater",
  "Rosso Vermouth",
  "Ruby Port",
  "Rum",
  "Rumple Minze",
  "Rye Whiskey",
  "Sake",
  "Salt",
  "Salted Chocolate",
  "Sambuca",
  "Sarsaparilla",
  "Schnapps",
  "Schweppes Lemon",
  "Schweppes Russchian",
  "Scotch",
  "Sherbet",
  "Sherry",
  "Singani",
  "Sirup of roses",
  "Sloe Gin",
  "Soda Water",
  "Sour Apple Pucker",
  "Sour Mix",
  "Southern Comfort",
  "Soy Milk",
  "Soy Sauce",
  "Soya Milk",
  "Soya Sauce",
  "Spiced Rum",
  "Sprite",
  "Squeezed Orange",
  "Squirt",
  "St. Germain",
  "Strawberries",
  "Strawberry Schnapps",
  "Strawberry juice",
  "Strawberry liqueur",
  "Strawberry syrup",
  "Sugar",
  "Sugar Syrup",
  "Sunny delight",
  "Surge",
  "Swedish punsch",
  "Sweet Cream",
  "Sweet Vermouth",
  "Sweet and Sour",
  "Tabasco Sauce",
  "Tang",
  "Tawny port",
  "Tea",
  "Tennessee whiskey",
  "Tequila",
  "Tequila rose",
  "Thyme",
  "Tia Maria",
  "Tomato",
  "Tomato Juice",
  "Tonic Water",
  "Triple Sec",
  "Tropicana",
  "Tuaca",
  "Vanilla",
  "Vanilla Ice-Cream",
  "Vanilla extract",
  "Vanilla liqueur",
  "Vanilla schnapps",
  "Vanilla syrup",
  "Vanilla vodka",
  "Vermouth",
  "Vinegar",
  "Vodka",
  "Water",
  "Watermelon",
  "Watermelon schnapps",
  "Whipped Cream",
  "Whipping Cream",
  "Whiskey",
  "Whisky",
  "White Creme de Menthe",
  "White Rum",
  "White Vermouth",
  "White Vinegar",
  "White Wine",
  "White chocolate liqueur",
  "White grape juice",
  "White port",
  "Wild Turkey",
  "Wildberry schnapps",
  "Wine",
  "Worcestershire Sauce",
  "Wormwood",
  "Yeast",
  "Yellow Chartreuse",
  "Yoghurt",
  "Yukon Jack",
  "Zima",
];
